In [ ]:
import numpy as np

In [ ]:
# arange(): range starts from 0(default) to n-1

In [ ]:
arr1= np.arange(10)
arr2=np.arange(4,10)
print(arr2)

[4 5 6 7 8 9]


In [ ]:
# arrays
# 1-d array

In [ ]:
arr1d=np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


In [ ]:
# accessing 1-d array

In [ ]:
print(arr1d[0])

1


In [ ]:
# for 2-d array: [[],[]]

In [ ]:
arr2d=np.array([[1,2,3],[2,3,4]])
print(arr2d)

[[1 2 3]
 [2 3 4]]


In [ ]:
# Properties of nd array

In [ ]:
# shape
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2d.shape

(2, 3)

In [ ]:
# dtype and astype
# arr_2d.dtype
arr_2d=arr_2d.astype(np.float32)
arr_2d.dtype

dtype('float32')

In [ ]:
# create 3d array=3 rows and n columns
arr_3d=np.zeros([2,3,4])
arr_3d

#size of array
arr_3d.size

#number of dimensions
arr_3d.ndim

3

In [ ]:
# create 4d array
arr_4d=np.ones([2,3,4,4])
arr_4d

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

# **Arithmetic operators**
**Addition**: np.add()

**Subtraction**: np.subtract()

**Multiplication**:np.multiply()

**Division**:np.divide()

**Modular Division**: np.mod()

**Exponent/Power**:np.pow()

##**Relational Operators**
**Equal** : ***==***

**Not Equal**: ***!=***

**Greater than**: ***>***

**Greater than or Equal to**: ***>=***

**Less than**: ***<***

**Less than or Equal to**: ***<=***

In [ ]:
# slice
arr=np.array([0,1,2,3,4,5])
print('sliced array : ',arr[1:4])
print('sliced array with step: ',arr[0:4:2])

sliced array :  [1 2 3]
sliced array with step:  [0 2]


In [ ]:
# negative indexing
arr=np.array([1,2,3,4,5])
print('negative indexed value ',arr[-2])

negative indexed value  4


In [ ]:
# masking
arr=np.array([1,2,3,4])
a=arr>3
arr[a]

array([4])

In [ ]:
# fancy indices
arr=np.array([1,2,3,4,5])
fancy=[0,1,2]
selected=arr[fancy]
selected

array([1, 2, 3])

In [ ]:
# transpose
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d.shape
transpose=arr2d.T
transpose.shape

(3, 2)

In [ ]:
# random number generation
# size represents count
rand=np.random.randint(1,10,size=4)
rand

#create a 2d array using random
rand2d=np.random.randint(1,10,size=(2,3))
rand2d

array([[2, 4, 7],
       [1, 6, 4]])

# **Operations** on 2d array:
**Matrix multiplication**: np.**matmul**()

**Reshape**: np.**reshape**()

Resize: np.**resize**()

Split: np.**split**()

same number matrix:np.**full**((size),num)

In [ ]:
# matrix multiplication

mat_a=np.array([[1,2],[3,4]])
mat_b=np.array([[4,5],[6,7]])
result=np.matmul(mat_a,mat_b)
result

array([[16, 19],
       [36, 43]])

In [ ]:
# reshape 2d array

arr=np.arange(10)
reshape=arr.reshape(2,5)
reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# resize

arr=np.arange(10)
arr.resize(2,7)
arr

array([[0, 1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 0, 0, 0]])

In [ ]:
#split

arr=np.arange(10)
# split_arr=np.split(arr,3)
# split_arr

#np.array_split
arr=np.array_split(arr,4)
arr

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [1]:
#initialize the array with same number
import numpy  as np
n2=np.full((2,3),5)
n2

array([[5, 5, 5],
       [5, 5, 5]])

#**Aggregate** Functions:
**sum** of elements in matrix: **np.sum()**

**max** of elements in matrix: **np.max()**

**min** of elements in matrix: **np.min()**

**mean** of elements in matrix: **np.mean()**

# **Joining** Arrays:


**np.vstack**( ) : row by row pile up

**np.hstack**( ) : all the rows in a single row

**np.column_stack**( ): rows in form of column

In [4]:
import numpy as np
n1=np.arange(10,40,10)
n2=np.arange(40,70,10)
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
import numpy as np
n1=np.arange(10,40,10)
n2=np.arange(40,70,10)
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [8]:
import numpy as np
n1=np.arange(10,40,10)
n2=np.arange(40,70,10)
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# **Addition** of numpy arrays:

**np.sum**( ) : sum of all elements in the arrays

**np.sum**(array1, array2, ***axis=0***): column wise addition for arrays

**np.sum**(array1, array2, ***axis=1***) : row wise addition for arrays

In [19]:
n1=np.array([10,20])
n2=np.array([30,40])
n1n2=np.sum([n1,n2])
n1n2

100

In [20]:
# column wise addition
n1n2=np.sum([n1,n2],axis=0)
n1n2

array([40, 60])

In [21]:
# row wise addition
n1n2=np.sum([n1,n2],axis=1)
n1n2

array([30, 70])