In [2]:
import numpy as np

In [3]:
# arange(): range starts from 0(default) to n-1

In [4]:
arr1= np.arange(10)
arr2=np.arange(4,10)
print(arr2)

[4 5 6 7 8 9]


In [5]:
# arrays
# 1-d array

In [6]:
arr1d=np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


In [7]:
# accessing 1-d array

In [8]:
print(arr1d[0])

1


In [9]:
# for 2-d array: [[],[]]

In [10]:
arr2d=np.array([[1,2,3],[2,3,4]])
print(arr2d)

[[1 2 3]
 [2 3 4]]


In [11]:
# Properties of nd array

In [12]:
# shape
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2d.shape

(2, 3)

In [13]:
# dtype and astype
# arr_2d.dtype
arr_2d=arr_2d.astype(np.float32)
arr_2d.dtype

dtype('float32')

In [19]:
# create 3d array=3 rows and n columns
arr_3d=np.zeros([2,3,4])
arr_3d

#size of array
arr_3d.size

#number of dimensions
arr_3d.ndim

3

In [20]:
# create 4d array
arr_4d=np.ones([2,3,4,4])
arr_4d

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

# **Arithmetic operators**
**Addition**: np.add()

**Subtraction**: np.subtract()

**Multiplication**:np.multiply()

**Division**:np.divide()

**Modular Division**: np.mod()

**Exponent/Power**:np.pow()

##**Relational Operators**
**Equal** : ***==***

**Not Equal**: ***!=***

**Greater than**: ***>***

**Greater than or Equal to**: ***>=***

**Less than**: ***<***

**Less than or Equal to**: ***<=***

In [24]:
# slice
arr=np.array([0,1,2,3,4,5])
print('sliced array : ',arr[1:4])
print('sliced array with step: ',arr[0:4:2])

sliced array :  [1 2 3]
sliced array with step:  [0 2]


In [25]:
# negative indexing
arr=np.array([1,2,3,4,5])
print('negative indexed value ',arr[-2])

negative indexed value  4


In [31]:
# masking
arr=np.array([1,2,3,4])
a=arr>3
arr[a]

array([4])

In [32]:
# fancy indices
arr=np.array([1,2,3,4,5])
fancy=[0,1,2]
selected=arr[fancy]
selected

array([1, 2, 3])

In [36]:
# transpose
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d.shape
transpose=arr2d.T
transpose.shape

(3, 2)

In [41]:
# random number generation
# size represents count
rand=np.random.randint(1,10,size=4)
rand

#create a 2d array using random
rand2d=np.random.randint(1,10,size=(2,3))
rand2d

array([[2, 4, 7],
       [1, 6, 4]])

# **Operations** on 2d array:
**Matrix multiplication**: np.**matmul**()

**Reshape**: np.**reshape**()

Resize: np.**resize**()

Split: np.**split**()

In [42]:
# matrix multiplication

mat_a=np.array([[1,2],[3,4]])
mat_b=np.array([[4,5],[6,7]])
result=np.matmul(mat_a,mat_b)
result

array([[16, 19],
       [36, 43]])

In [46]:
# reshape 2d array

arr=np.arange(10)
reshape=arr.reshape(2,5)
reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
# resize

arr=np.arange(10)
arr.resize(2,7)
arr

array([[0, 1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 0, 0, 0]])

In [62]:
#split

arr=np.arange(10)
# split_arr=np.split(arr,3)
# split_arr

#np.array_split
arr=np.array_split(arr,4)
arr

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

# **Aggregate** Functions:
**sum** of elements in matrix: **np.sum()**

**max** of elements in matrix: **np.max()**

**min** of elements in matrix: **np.min()**

**mean** of elements in matrix: **np.mean()**